### ISSUE TITLE
error pl.txt

### ISSUE THREAD

**Issue by weiwang999** [DirajHS/MP4_Streamer#1]
weiwang99@cs000061:~/Video-Streaming-master$ ./st localhost 9001 /h pl.txt
ERROR: Error opening pl.txt
No such file or directory

**Comment by DirajHS** [comment]
@weiwang999 , `pl.txt` should be created by you which contains the absolute path to the video file which you want to stream. 
My bad that I haven't mentioned it in README, will update soon :smiley:
